### ISSUE TITLE
Can l work in Catalina 10.15.4？

### ISSUE THREAD

**Issue by AAedionfree** [lakshayg/tensorflow-build#1]
tensorflow version = 1.14.0

**Comment by lakshayg** [comment]
I'm not sure but it might work. Could you give it a try and let me know if it does not?

**Comment by AAedionfree** [comment]
@lakshayg Hackintosh Caralina 10.15.4, work well.

**Comment by AAedionfree** [comment]
> I'm not sure but it might work. Could you give it a try and let me know if it does not?

Hackintosh 10.15.4 Catalina, work well.
