### ISSUE TITLE
Add 1.14.1 Ubuntu Build

### ISSUE THREAD

**Issue by LumaRay** [lakshayg/tensorflow-build#2]
Hi!
I see you have this build:
1.14.1 | CPU | Ubuntu 18.04 | 7.4 | 3.7.3 | FMA, AVX2, AVX512F
But my CPU doesn't support AVX512F
Can you add this one?
1.14.1 | CPU | Ubuntu 18.04 | 7.4 | 3.7.3 | FMA, AVX, AVX2, SSE4.1, SSE4.2

**Comment by lakshayg** [comment]
Hi there. I have a build for tensorflow 2.3.0-rc0 which I have added (note that this is a pre-release build)

https://github.com/lakshayg/tensorflow-build/releases/download/tf2.3.0rc0-py3.7-ubuntu18.04/tensorflow-2.3.0rc0-cp37-cp37m-linux_x86_64.whl

Ubuntu 18.04
Python 3.7.7
Flags: FMA, AVX, AVX2, SSE4.1, SSE4.2
gcc 7.5

Please let me know if this works for you. I'll also be adding a build for TF 2.2.0 soon

**Comment by lakshayg** [comment]
I've added TF 2.2.0 for ubuntu 18.04, python 3.7.7
https://github.com/lakshayg/tensorflow-build/releases/download/tf2.2.0-py3.7-ubuntu18.04/tensorflow-2.2.0-cp37-cp37m-linux_x86_64.whl

**Comment by LumaRay** [comment]
Hi! I have successfully installed "tensorflow 2.3.0-rc0"! Thank you!!
Debian 10.4 x64
Python 3.7.3
gcc 8.3.0
