### ISSUE TITLE
Compilation flags/options

### ISSUE THREAD

**Issue by fenz** [lakshayg/tensorflow-build#4]
The table you add in the README is a nice overview of the build content but I guess it would be useful to document also the command you used for the build with all the options (--config=mkl? --config=numa?  --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0? --copt=-O3?)

**Comment by fenz** [comment]
For my request I was thinking something like this: https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html
("Build from source" section)

**Comment by lakshayg** [comment]
I have added this in the latest commit
