### ISSUE TITLE
Q9550 (no avx) build for ubuntu 18.04

### ISSUE THREAD

**Issue by loretoparisi** [lakshayg/tensorflow-build#6]
My system has a Intel Quad Core Q9550 cpu that has no AVX instructions support. A nvidia geForce GTX 1050 ti gpu is also available.
The cpu flags are:

```
loreto@ombromanto:~$ grep flags -m1 /proc/cpuinfo | cut -d ":" -f 2 | tr '[:upper:]' '[:lower:]' | { read FLAGS; OPT="-march=native"; for flag in $FLAGS; do case "$flag" in "sse4_1" | "sse4_2" | "ssse3" | "fma" | "cx16" | "popcnt" | "avx" | "avx2") OPT+=" -m$flag";; esac; done; MODOPT=${OPT//_/\.}; echo "$MODOPT"; }
-march=native -mssse3 -mcx16 -msse4.1

```

Which is the most 
 recent linux (ubuntu 18.04) tensorflow gpu binary build that would run on this cpu?

Thank you.

**Comment by lakshayg** [comment]
Unfortunately, none of the binaries linked in this repository will work because all of the have AVX support. Since you have a GPU, you should look for binaries with GPU support to make the most of your hardware. This repository only provides CPU builds.

**Comment by loretoparisi** [comment]
@lakshayg thank you, the strange thing with GPU build, is that even if I target the gpu binary build, the error is still there, since anyways the bazel build will have the same cpu flags of the gpu build...
