### ISSUE TITLE
Issue with numpy version

### ISSUE THREAD

**Issue by josemarfdc** [lakshayg/tensorflow-build#9]
Thanks for putting this up.

I'm having issue with the numpy version. I didn't really specify a numpy version, I just installed the whl file and let pip install whichever numpy it deemed appropriate. However, when I try to import tensorflow, I face this issue:

```python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.19.5'

In [3]: import tensorflow
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core._multiarray_umath failed to import
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.umath failed to import
2021-11-23 21:55:55.206575: F tensorflow/python/lib/core/bfloat16.cc:714] Check failed: PyBfloat16_Type.tp_base != nullptr 
Aborted (core dumped)
```

The binary which seems to refer to the numpy version is very confusing 0xe = 14 and 0xd = 13, but as you can see, my numpy version is 1.19.5

OS info:
```bash
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

CPU flags
```bash
model name	: AMD Ryzen 9 3900X 12-Core Processor
stepping	: 0
microcode	: 0x8701021
cpu MHz		: 4098.697
cache size	: 512 KB
physical id	: 0
siblings	: 24
core id		: 14
cpu cores	: 12
apicid		: 29
initial apicid	: 29
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 
ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf 
pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm 
extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext 
perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 
cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc 
cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale 
vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov 
succor smca
```

Any help is much appreciated

**Comment by lakshayg** [comment]
I'm not sure what's happening here but I have a few thoughts:
1. All the binaries here have been compiled on an Intel machine and it looks like you are using an AMD machine. I'm not sure if that's going to be an issue, just something to note
2. Could you try upgrading to the latest numpy version? Does that solve the issue?
3. If none of this works, I'm planning to build a new binary with the most recent versions of all the dependencies. I can update here when it is ready.

**Comment by josemarfdc** [comment]
Thanks for the reply. 

Updating to Numpy 1.21.4 (latest stable version on PyPI as of this writing) solved the problem, at least as far as import goes. 

```bash
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.21.4'

In [3]: import tensorflow

In [4]: 
```
`pip` 's dependency resolver complains about a conflict between tensorflow 2.4.1 and numpy 1.21.4. I hope this is only because of the requirement version which is manually set in the TF installer, and not about some real incompatibility between these versions.
```bash
(tfcpu) linuxuser@ubuntulinux:~$ pip install numpy==1.21.4
Collecting numpy==1.21.4
  Using cached numpy-1.21.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Installing collected packages: numpy
  Attempting uninstall: numpynux:~$ pip install numpy==1.21.4

Collecting numpy==1.21.4
  Using cached numpy-1.21.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.4.1 requires numpy~=1.19.2, but you have numpy 1.21.4 which is incompatible.
```
This installation was done in a brand new miniconda env. Because I didn't have numpy, when I installed the TF whl, pip automatically pulled a numpy version that met the requirements set for TF, which led to the issue.

It appears that TF was compiled against a version of numpy which is different than the version requirements for TF? 

As a way to prevent this issue, I suggest you add in the README, the numpy version, and the versions of other dependencies, against which the TF whl was compiled.

BTW, I tested it and the same issue happens on a Intel machine and it's solved the exact same way.

Thanks again for putting this up. I'm just so happy to avoid having to deal with basel and the whole ordeal that comes with building tensorflow.

**Comment by lakshayg** [comment]
Here' the latest build for Ubuntu 20.04: https://github.com/lakshayg/tensorflow-build/releases/tag/tf2.7.0-ubuntu20.04-py3.8.10
